#!/usr/bin/env bash
#This script installs nginx and configures it

sudo apt-get -y update
sudo apt-get -y install nginx

echo -e "Helllo World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
