#!/usr/bin/env bash
# This bash script configures nginx to open port 80 properly
rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
