#!/usr/bin/env bash
# This script displays the content of the current directory
#in a list format

for file in *; do
    if [[ ! "$file" =~ ^\. && "$file" =~ - ]]; then
        new_name="${file#*-}"
        echo "$new_name"
    fi
done