#!/usr/bin/env bash
#This Bash script configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.n

echo "8.8.8.8 facebook.com" >> ~/hosts.n
sed -i "s/"127.0.0.1"/"127.0.0.2"/g" ~/hosts.n

cp -f ~/hosts.n /etc/hosts
